Issue #38: Implement endpoints related to Processes
averbis/averbis-python-api pull request #39
Opened 2021-04-27 12:41 UTC by nadre

This pull request contains the implementation of the new endpoints as described in Issue #38

2021-04-27 13:29 UTC, Philly-B commented
Test

2021-04-28 05:15 UTC, reckart commented
Please run "make black" for auto-formatting.

2021-04-28 07:50 UTC, reckart commented
I have changed the target branch from main to dev - PRs should go to dev. Main should always be the latest release version... I also make the mistake sometimes.... we need to pay attention.

Can you please merge the latest change from dev into your branch, resolve conflicts, `make black` and then re-request the review. Thanks!

2021-04-28 08:00 UTC, reckart requested changes
Many method do not have pydoc.

2021-04-28 08:00 UTC, reckart commented on averbis/core/_rest_client.py
> +    def list_processes(self) -> List[Tuple[str, str]]:
I'd prefer returing a `List[Process]` or possibly a  `list_process_states()` returning `List[ProcessState]` - in the latter case, I'd also like a method `ProcessState.get_process()` so I can access the actual process from the process state.

2021-04-28 08:00 UTC, reckart commented on averbis/core/_rest_client.py
> +                 state: str,
As a user, I expect that I can call `process.get_state()` and then get e.g. a `ProcessState` object back which includes the state and the number of documents that have been processed. The information should always be freshly fetched from the server so I can monitor by repeatedly calling `process.get_state()`. I.e. `state` and `processed_documents` should not be constructor arguments and should not be saved within the `Process` class on the Python side.

2021-04-28 08:00 UTC, reckart commented on averbis/core/_rest_client.py
> +    def reprocess(self):
As a user, I am confused when I see `reprocess` because I seriously wonder how I can trigger the first processing... because for a **reprocessing**, the **processing** must already have been performed once, right?

I'd prefer this method be called `start()`  -> `process.start()`. That makes clear to me that an asynchronous process is started. It also makes me wonder where the `stop()` method is.

2021-04-28 08:10 UTC, nadre commented on averbis/core/_rest_client.py
> +    def list_processes(self) -> List[Tuple[str, str]]:
We thought about this one too. A List[Process] totally makes sense, it just requires another backend call for each process. But that should not be a problem.

2021-04-28 08:15 UTC, nadre commented on averbis/core/_rest_client.py
> +                 state: str,
I totally see the point but I'm not sure if it is worth opening the gap between client and product api.

2021-04-28 08:16 UTC, nadre commented on averbis/core/_rest_client.py
> +    def reprocess(self):
The process starts as soon as it is created. stop() is not implemented yet.

2021-04-28 08:44 UTC, reckart commented on averbis/core/_rest_client.py
> +    def list_processes(self) -> List[Tuple[str, str]]:
Why does it require another backend call for each process? I'd expect that a `list_processes` REST API endpoint provides sufficient information to instantiate a `Process` python object.

2021-04-28 08:45 UTC, reckart commented on averbis/core/_rest_client.py
> +                 state: str,
Yes, totally :) You can also change the REST API if you like :P

2021-04-28 09:06 UTC, reckart commented on averbis/core/_rest_client.py
> +    def reprocess(self):
Can we have a `stop()`? 🥺

2021-04-28 09:09 UTC, reckart commented on averbis/core/_rest_client.py
> +    def reprocess(self):
Suppose I'd like to hack myself a `stop()` - what happens if I do this?

```
process = project.createProcess("my-process")
process.start()
process.delete()
process = project.createProcess("my-process")
```

2021-04-28 09:10 UTC, reckart commented on averbis/core/_rest_client.py
> +                 state: str,
Actually, we already have a two-layer architecture in the Python API.

At the low level is the `Client` which more-or-less resembles exactly the endpoints as provided by the product. 
At the high level, we have the convenience objects like `Project` or `Process` which aim to make the whole thing more user-friendly for the Python programmer. So we do have a place for that gap you mention already and use it - intentionally.

2021-04-28 09:20 UTC, reckart commented on averbis/core/_rest_client.py
> +    def reprocess(self):
I find it very strange/inconvenient that a process is started immediately upon creation. I'd expect that the process is created and then can be started separately.

2021-04-28 09:25 UTC, reckart commented on averbis/core/_rest_client.py
> +    def reprocess(self):
At the very least, I would then expect that `project.create_process()` rather be called`project.start_new_process()`.

2021-04-28 13:34 UTC, nadre commented on averbis/core/_rest_client.py
> +    def list_processes(self) -> List[Tuple[str, str]]:
done.

2021-04-28 13:34 UTC, nadre commented on averbis/core/_rest_client.py
> +                 state: str,
done.

2021-04-28 13:35 UTC, nadre commented on averbis/core/_rest_client.py
> +    def reprocess(self):
out of scope.

2021-04-28 15:02 UTC, nadre commented
@reckart & @Philly-B I think I'm done here. Please check and merge if everything's fine.

2021-04-28 15:16 UTC, reckart approved these changes

2021-04-28 15:17 UTC, reckart commented
@Philly-B fine by me - would you like to give a thumbs up as well and merge?

2021-05-05 15:08 UTC, merged